// Theme palettes ported exactly from the original bundle's theme object
// (found as the literal `pn` object literal in index-XLkmhznS.js — 8
// palettes, "Navy Dark" first/default). Every hex value below was read
// straight out of that object, not approximated — if a token is needed that
// isn't here, it doesn't exist in the original and shouldn't be invented.
//
export const THEMES = {
  "Navy Dark": {
    appBg: "#0A1628",
    sidebarBg: "#0D1E35",
    cardBg: "#0D1E35",
    topbarBg: "#0D1E35",
    border: "#1E3A5F",
    border2: "#1A2E45",
    inputBg: "#0A1628",
    metricBg: "#0A1628",
    textPrimary: "#E8F4FD",
    textSecondary: "#8BAFC8",
    textMuted: "#6B8CAE",
    textHighlight: "#FFFFFF",
    textSubtle: "#4A6A8A",
    accent: "#00B4D8",
    accentText: "#0A1628",
    navActive: "rgba(0,180,216,0.12)",
    tableHead: "#0A1628",
    tableRow: "#0D1E35",
    tableRowAlt: "#0F2440",
    tableHover: "#15304F",
    scrollThumb: "#1E3A5F",
    cardSubBg: "#0A1A2E",
    infoBarBg: "#0E2A45",
    codeBg: "#060E1A",
    codeText: "#6BCF9E",
    danger: "#E63946",
    warning: "#F4A261",
    success: "#2DC653",
    info: "#00B4D8",
    dangerBg: "#3A1A1A",
    warningBg: "#3A2A1A",
    successBg: "#1A3A2A",
    pillDanger: "#E63946",
    pillWarning: "#F4A261",
    pillSuccess: "#2DC653",
    pillInfo: "#00B4D8",
    purple: "#A78BFA",
    purpleBg: "#2A1A45",
    pillPurple: "#A78BFA",
  },
  "Midnight Blue": {
    appBg: "#0D0F1A",
    sidebarBg: "#12152B",
    cardBg: "#12152B",
    topbarBg: "#12152B",
    border: "#252A4A",
    border2: "#1C2040",
    inputBg: "#0D0F1A",
    metricBg: "#0D0F1A",
    textPrimary: "#E6E8FF",
    textSecondary: "#9499D0",
    textMuted: "#7B82C0",
    textHighlight: "#FFFFFF",
    textSubtle: "#4A5080",
    accent: "#7C6FE6",
    accentText: "#FFFFFF",
    navActive: "rgba(124,111,230,0.14)",
    tableHead: "#0D0F1A",
    tableRow: "#12152B",
    tableRowAlt: "#161A35",
    tableHover: "#1E2244",
    scrollThumb: "#252A4A",
    cardSubBg: "#0D0F1A",
    infoBarBg: "#1A1E40",
    codeBg: "#080A14",
    codeText: "#A78BFA",
    danger: "#F0556D",
    warning: "#F5A65B",
    success: "#3DDC84",
    info: "#7C6FE6",
    dangerBg: "#321828",
    warningBg: "#332416",
    successBg: "#15301F",
    pillDanger: "#F0556D",
    pillWarning: "#F5A65B",
    pillSuccess: "#3DDC84",
    pillInfo: "#7C6FE6",
    purple: "#C084FC",
    purpleBg: "#341A45",
    pillPurple: "#C084FC",
  },
  "Forest Green": {
    appBg: "#0A1A12",
    sidebarBg: "#0D2019",
    cardBg: "#0D2019",
    topbarBg: "#0D2019",
    border: "#1A3A28",
    border2: "#152E20",
    inputBg: "#0A1A12",
    metricBg: "#0A1A12",
    textPrimary: "#E8F5EE",
    textSecondary: "#8FC2A3",
    textMuted: "#5A9A70",
    textHighlight: "#FFFFFF",
    textSubtle: "#3A6A50",
    accent: "#2DC653",
    accentText: "#0A1A12",
    navActive: "rgba(45,198,83,0.12)",
    tableHead: "#0A1A12",
    tableRow: "#0D2019",
    tableRowAlt: "#0F2620",
    tableHover: "#163A2C",
    scrollThumb: "#1A3A28",
    cardSubBg: "#081410",
    infoBarBg: "#123524",
    codeBg: "#060F09",
    codeText: "#6BCF9E",
    danger: "#E66464",
    warning: "#E6B45A",
    success: "#2DC653",
    info: "#4FB8E0",
    dangerBg: "#3A1A1A",
    warningBg: "#3A2E16",
    successBg: "#173A24",
    pillDanger: "#E66464",
    pillWarning: "#E6B45A",
    pillSuccess: "#2DC653",
    pillInfo: "#4FB8E0",
    purple: "#B388EB",
    purpleBg: "#2A1A3A",
    pillPurple: "#B388EB",
  },
  "Carbon Dark": {
    appBg: "#0A0A0A",
    sidebarBg: "#111111",
    cardBg: "#1A1A1A",
    topbarBg: "#111111",
    border: "#2A2A2A",
    border2: "#222222",
    inputBg: "#0A0A0A",
    metricBg: "#111111",
    textPrimary: "#E5E5E5",
    textSecondary: "#A0A0A0",
    textMuted: "#6A6A6A",
    textHighlight: "#FFFFFF",
    textSubtle: "#808080",
    accent: "#F5A623",
    accentText: "#0A0A0A",
    navActive: "rgba(245,166,35,0.12)",
    tableHead: "#0A0A0A",
    tableRow: "#1A1A1A",
    tableRowAlt: "#141414",
    tableHover: "#222222",
    scrollThumb: "#333333",
    cardSubBg: "#111111",
    infoBarBg: "#161616",
    codeBg: "#050505",
    codeText: "#F5A623",
    danger: "#FF4444",
    warning: "#F5A623",
    success: "#44CC44",
    info: "#44AAFF",
    dangerBg: "#2A1010",
    warningBg: "#2A2000",
    successBg: "#102A10",
    pillDanger: "#FF4444",
    pillWarning: "#F5A623",
    pillSuccess: "#44CC44",
    pillInfo: "#44AAFF",
    purple: "#BB86FC",
    purpleBg: "#1E1030",
    pillPurple: "#BB86FC",
  },
  "Slate Light": {
    appBg: "#F0F4F8",
    sidebarBg: "#FFFFFF",
    cardBg: "#FFFFFF",
    topbarBg: "#FFFFFF",
    border: "#D0DDE8",
    border2: "#E0EAF0",
    inputBg: "#F8FAFC",
    metricBg: "#F8FAFC",
    textPrimary: "#0F172A",
    textSecondary: "#475569",
    textMuted: "#8899AA",
    textHighlight: "#0F172A",
    textSubtle: "#0F172A",
    accent: "#0078A0",
    accentText: "#FFFFFF",
    navActive: "rgba(0,120,160,0.10)",
    tableHead: "#F0F4F8",
    tableRow: "#FFFFFF",
    tableRowAlt: "#F6FAFD",
    tableHover: "#E8F2F8",
    scrollThumb: "#C0D0DC",
    cardSubBg: "#F4F8FB",
    infoBarBg: "#E6F2F8",
    codeBg: "#EEF4F8",
    codeText: "#006080",
    danger: "#D62839",
    warning: "#D9822B",
    success: "#1E9E5A",
    info: "#0078A0",
    dangerBg: "#FBE4E6",
    warningBg: "#FDF0DF",
    successBg: "#E2F5EA",
    pillDanger: "#D62839",
    pillWarning: "#D9822B",
    pillSuccess: "#1E9E5A",
    pillInfo: "#0078A0",
    purple: "#7C3AED",
    purpleBg: "#EFE6FB",
    pillPurple: "#7C3AED",
  },
  "Pearl White": {
    appBg: "#F8F9FA",
    sidebarBg: "#FFFFFF",
    cardBg: "#FFFFFF",
    topbarBg: "#FFFFFF",
    border: "#DDE3EA",
    border2: "#EBF0F5",
    inputBg: "#F4F6F9",
    metricBg: "#F4F6F9",
    textPrimary: "#1A1F2E",
    textSecondary: "#4B5563",
    textMuted: "#9CA3AF",
    textHighlight: "#0F172A",
    textSubtle: "#1A1F2E",
    accent: "#4361EE",
    accentText: "#FFFFFF",
    navActive: "rgba(67,97,238,0.10)",
    tableHead: "#F4F6F9",
    tableRow: "#FFFFFF",
    tableRowAlt: "#F9FAFB",
    tableHover: "#EEF2FF",
    scrollThumb: "#CBD5E1",
    cardSubBg: "#F4F6F9",
    infoBarBg: "#EEF2FF",
    codeBg: "#F1F5F9",
    codeText: "#1E40AF",
    danger: "#DC2626",
    warning: "#D97706",
    success: "#16A34A",
    info: "#4361EE",
    dangerBg: "#FEE2E2",
    warningBg: "#FEF3C7",
    successBg: "#DCFCE7",
    pillDanger: "#DC2626",
    pillWarning: "#D97706",
    pillSuccess: "#16A34A",
    pillInfo: "#4361EE",
    purple: "#7C3AED",
    purpleBg: "#EDE9FE",
    pillPurple: "#7C3AED",
  },
  "Sky Blue": {
    appBg: "#EFF6FF",
    sidebarBg: "#DBEAFE",
    cardBg: "#FFFFFF",
    topbarBg: "#FFFFFF",
    border: "#BFDBFE",
    border2: "#DBEAFE",
    inputBg: "#F0F9FF",
    metricBg: "#F0F9FF",
    textPrimary: "#0F172A",
    textSecondary: "#1E40AF",
    textMuted: "#3B82F6",
    textHighlight: "#0F172A",
    textSubtle: "#0F172A",
    accent: "#2563EB",
    accentText: "#FFFFFF",
    navActive: "rgba(37,99,235,0.12)",
    tableHead: "#EFF6FF",
    tableRow: "#FFFFFF",
    tableRowAlt: "#F0F9FF",
    tableHover: "#DBEAFE",
    scrollThumb: "#93C5FD",
    cardSubBg: "#F0F9FF",
    infoBarBg: "#DBEAFE",
    codeBg: "#EFF6FF",
    codeText: "#1E40AF",
    danger: "#DC2626",
    warning: "#D97706",
    success: "#16A34A",
    info: "#2563EB",
    dangerBg: "#FEE2E2",
    warningBg: "#FEF3C7",
    successBg: "#DCFCE7",
    pillDanger: "#DC2626",
    pillWarning: "#D97706",
    pillSuccess: "#16A34A",
    pillInfo: "#2563EB",
    purple: "#7C3AED",
    purpleBg: "#EDE9FE",
    pillPurple: "#7C3AED",
  },
  "Warm Sand": {
    appBg: "#F5F0E8",
    sidebarBg: "#FFF8F0",
    cardBg: "#FFF8F0",
    topbarBg: "#FFF8F0",
    border: "#D8C8A8",
    border2: "#E8D8B8",
    inputBg: "#FFFFFF",
    metricBg: "#FAF4EC",
    textPrimary: "#2A1A08",
    textSecondary: "#6A5238",
    textMuted: "#8A7458",
    textHighlight: "#0F172A",
    textSubtle: "#2A1A08",
    accent: "#B5651D",
    accentText: "#FFFFFF",
    navActive: "rgba(181,101,29,0.12)",
    tableHead: "#F5F0E8",
    tableRow: "#FFF8F0",
    tableRowAlt: "#FAF1E0",
    tableHover: "#F0E2C8",
    scrollThumb: "#D8C8A8",
    cardSubBg: "#FAF4EC",
    infoBarBg: "#F3E6D2",
    codeBg: "#FAF4EC",
    codeText: "#8A4B0A",
    danger: "#C0392B",
    warning: "#C77A1F",
    success: "#3A8753",
    info: "#3072A8",
    dangerBg: "#F8E0DC",
    warningBg: "#F8EBD8",
    successBg: "#E2F0E5",
    pillDanger: "#C0392B",
    pillWarning: "#C77A1F",
    pillSuccess: "#3A8753",
    pillInfo: "#3072A8",
    purple: "#7C3AED",
    purpleBg: "#EDE2FB",
    pillPurple: "#7C3AED",
  },
};

export const DEFAULT_THEME = "Navy Dark";
export const THEME_NAMES = Object.keys(THEMES);

// Fallback used before the ThemeProvider has resolved a stored theme name
// (e.g. very first paint) and by any legacy call site not yet passed
// through useTheme().
export const T = THEMES[DEFAULT_THEME];

// Builds the small set of reusable inline-style shapes the original app
// derives from the active palette (background/border/radius/padding
// combos for cards, buttons, inputs, etc). In the original bundle these are
// served by a `new Proxy({}, { get(target, key) {...} })` keyed on the
// *current* theme object, so switching themes updates every already-mounted
// component without those components re-deriving anything themselves. A
// React accessor object serves the same purpose more idiomatically:
// ThemeContext recomputes this once per theme change (see ThemeContext.jsx)
// and every component reads from the resulting `s` object.
export function buildStyles(T) {
  return {
    page: { background: T.appBg, minHeight: "100%", color: T.textPrimary },
    card: { background: T.cardBg, border: `1px solid ${T.border}`, borderRadius: 10, padding: 16 },
    cardSub: { background: T.cardSubBg, border: `1px solid ${T.border2}`, borderRadius: 8, padding: 12 },
    btn: {
      background: T.accent,
      color: T.accentText,
      border: "none",
      borderRadius: 8,
      padding: "8px 14px",
      fontSize: 13,
      fontWeight: 600,
      cursor: "pointer",
    },
    btnSecondary: {
      background: "transparent",
      color: T.textPrimary,
      border: `1px solid ${T.border}`,
      borderRadius: 8,
      padding: "8px 14px",
      fontSize: 13,
      fontWeight: 600,
      cursor: "pointer",
    },
    btnDanger: {
      background: "transparent",
      color: T.danger,
      border: `1px solid ${T.danger}`,
      borderRadius: 8,
      padding: "8px 14px",
      fontSize: 13,
      fontWeight: 600,
      cursor: "pointer",
    },
    btnSm: {
      background: T.accent,
      color: T.accentText,
      border: "none",
      borderRadius: 6,
      padding: "5px 10px",
      fontSize: 12,
      fontWeight: 600,
      cursor: "pointer",
    },
    input: {
      background: T.inputBg,
      color: T.textPrimary,
      border: `1px solid ${T.border}`,
      borderRadius: 6,
      padding: "8px 10px",
      fontSize: 13,
      width: "100%",
      boxSizing: "border-box",
    },
    label: { fontSize: 12, color: T.textSecondary, marginBottom: 4, display: "block", fontWeight: 600 },
    metric: { background: T.metricBg, border: `1px solid ${T.border}`, borderRadius: 10, padding: "14px 16px" },
  };
}

// Small pill/badge helper shared by status chips (StatusBadge, count
// badges in the sidebar) — `color + "22"` appends a ~13% alpha hex suffix
// for the background, exactly as the original's `Gn()` helper does.
export function pillStyle(color) {
  return {
    background: color + "22",
    color,
    borderRadius: 999,
    padding: "2px 10px",
    fontSize: 11,
    fontWeight: 700,
    display: "inline-block",
    whiteSpace: "nowrap",
  };
}
